apiVersion: v1 
kind: Service
metadata: 
  name: bootcamp
  labels:
    role: frontend
    env: demo
spec: 
   type: NodePort
   ports: 
    - protocol: TCP
      port: 3000
   selector:     
    role: frontend