apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot1
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: malyadr/greenboot:1
        env:   
           - name: SPRING_DATASOURCE_URL
             value: jdbc:postgresql://db:5432/jobs
           - name: SPRING_DATASOURCE_USERNAME
             value: jobs_usr    
           - name: SPRING_DATASOURCE_PASSWORD
             value: us3rs
           - name: SPRING_JPA_HIBERNATE_DDL_AUTO
             value: update
        ports:
        - containerPort: 8080