name: frontend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login to dockerhub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_HUB_PASSWD }}   
      run:
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWD

    - name: build the docker image 
      run: docker build . --tag malyadr/frontend

    - name: docker push
      run: docker push ${{ secrets.DOCKER_HUB_USER }}/frontend  
 