name: frontend

on:
  push:
    branches: [ master ]

 jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
      # mockdir folder working directory.
        working-directory: web-ui

    steps:
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
         
     - name: build the docker image 
       run: docker build . -t  malyadr/frontend

     - name: docker push
       run: docker push ${{ secrets.DOCKER_HUB_USER }}/frontend  

  jobs:       
    build:
     runs-on: ubuntu-latest
     defaults:
      run:
      # mockdir folder working directory.
        working-directory: services/job-management-service

     steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: build the docker image 
        run: docker build . -t  malyadr/frontend

      - name: docker push
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/frontend  

    jobs:
     deploy:
       runs-on: ubuntu-latest

   steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: configure AWS credentials
       uses: aws-actions/configure-aws-credentials
       with: 
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
     - name: connect to EKS cluster
       run: aws eks --region $EKS_REGION update-kubeconfig --name $EKS_CLUSTER    
              

   
      






 